# Generated by Django 5.0.1 on 2024-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasAPP', '0002_alter_reservas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estadoReserva',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Completada', 'Completada'), ('Anulada', 'Anulada'), ('No asisten', 'No asisten')], max_length=100),
        ),
    ]
