# Generated by Django 5.0.1 on 2024-12-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasAPP', '0004_alter_reservas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
