# Generated by Django 5.0.1 on 2024-12-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasAPP', '0006_alter_reservas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cantidadPersonas',
            field=models.IntegerField(max_length=15),
        ),
    ]
